//
// Created by fengbo on 2020/5/31.
//

#ifndef TINYRENDERPRACTICE_L1_BRESENHAM_LINE_ALGORITHM_H
#define TINYRENDERPRACTICE_L1_BRESENHAM_LINE_ALGORITHM_H


class L1_Bresenham_Line_Algorithm {

};


#endif //TINYRENDERPRACTICE_L1_BRESENHAM_LINE_ALGORITHM_H
